### PR TITLE
create asev3 blog

### PR DESCRIPTION
**Pull request by ccompy**

### CODE REVIEW

**Comment by ccompy** [comment]
toggling to see if it will launch the preview

**Comment by ccompy** [comment]
reopening

**Comment by ccompy** [comment]
it does not want to do a preview for the site. Would prefer to see the preview before sign-off

**Comment by ccompy** [comment]
looks like it is sad because it cannot make more slots for the standard SKU it is being deployed into.

**Comment by JasonFreeberg** [comment]
## [Preview link](https://antares-blog-staging-pr-136.azurewebsites.net) 
- Your changes have been deployed to the preview site. The preview site will update as you add more commits to this branch. 
- The preview site shows any future-dated articles. Don't worry, if you are publishing a future-dated article, it will not show on the production site until the file's specified date.
- The preview link is shareable, but will be deleted when the pull request is merged or closed.
> *This is an automated message.*

**Pull request closed without merging**
