### PR TITLE
Added option for Windows containers

### PR DESCRIPTION
**Pull request by tulikac**

### CODE REVIEW

**Review by jvano — APPROVED** [review]
Looks good to me. :shipit:

**Review by btardif — CHANGES_REQUESTED** [review]
It's good, just need to remove the `/en-us/` segment from URL.

This makes it so that folks get routed to localized content if it exists.

**Comment by tulikac** [comment]
Removed en-us

**Review by btardif — APPROVED** [review]

**Comment by btardif** [comment]
FYI @tulikac , @jvano  change is merged 👍🏻

**Pull request merged**
