### PR TITLE
Adding a new article about Proactive CPU Monitoring

### PR DESCRIPTION
**Pull request by yunjchoi**
Adding a new blog about Proactive CPU Monitoring

This is a request to publish an article.

## Summary

Adding a new article about Proactive CPU Monitoring

### CODE REVIEW

**Comment by yunjchoi** [comment]
Hi @JasonFreeberg, 
can you please take a look at my PR and merge it if all looks good? Thank you!

**Comment by yunjchoi** [comment]
Added UserVoice link in the blog. @JasonFreeberg Can you review my PR? Thank you so much in advance!

**Comment by JasonFreeberg** [comment]
@yunjchoi are you okay with my edits? See the opening sentence. The other edits are minor

**Comment by yunjchoi** [comment]
@JasonFreeberg Looks good to me! Thank you for reviewing my article :)

**Pull request merged**
